name: build-new-style

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: 'adafruit:nrf52:pca10056'
            artifact: 'SoftRF-nrf52'
            path: 'adafruit.nrf52.pca10056'
          - board: 'esp32:esp32:esp32:PartitionScheme=min_spiffs,CPUFreq=80,PSRAM=enabled,FlashFreq=80,FlashMode=dio,FlashSize=4M,DebugLevel=none'
            artifact: 'SoftRF-esp32'
            path: 'esp32.esp32.esp32'
          - board: 'esp32:esp32:esp32s3:PartitionScheme=default_8MB,CPUFreq=80,PSRAM=enabled,FlashMode=qio,FlashSize=8M,DebugLevel=none,CDCOnBoot=cdc,USBMode=hwcdc'
            artifact: 'SoftRF-esp32s3'
            path: 'esp32.esp32.esp32s3'
    env:
      BOARD: ${{ matrix.board }}
      ARTIFACT: ${{ matrix.artifact }}
    steps:
      - name: Install rename
        run: sudo apt-get install -y rename
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-environment
        with:
          board: ${{ matrix.board }}
      - name: Build SoftRF for platform ${{ matrix.board }}
        run: |
          echo 'Building board ${{ matrix.board }}'
          cd $GITHUB_WORKSPACE
          arduino-cli compile -e -b "${{ matrix.board }}" $GITHUB_WORKSPACE/software/firmware/source/SoftRF
      - name: Running uf2 for nrf52
        if: startsWith(matrix.board, 'adafruit:nrf52:')
        run: |
          shopt -s extglob
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/${{ matrix.path }}"
          ~/uf2/utils/uf2conv.py SoftRF.ino.hex -c -f 0xADA52840 -o SoftRF.uf2
          rm -v !("SoftRF.uf2")
      - name: Running uf2 for esp32s3
        if: startsWith(matrix.board, 'esp32:esp32:esp32s3')
        run: |
          shopt -s extglob
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/${{ matrix.path }}"
          ~/uf2/utils/uf2conv.py SoftRF.ino.bin -b 0x00 -c -f 0xc47e5767 -o SoftRF.uf2
      - name: Rename before artifact upload
        run: |
          shopt -s extglob
          cd "$GITHUB_WORKSPACE/software/firmware/source/SoftRF/build/${{ matrix.path }}"
          # Rename to the right file type, we do this for clarity of the files
          rename -v 's/SoftRF/${{ matrix.artifact }}/' SoftRF*
          # Create a zip with the contents so that the download artifact just get zipfiles
          zip -r ${{ matrix.artifact }}.zip .
          rm -v !("${{ matrix.artifact }}.zip")
      - uses: actions/upload-artifact@v3
        with:
          name: SoftRF
          path: |
            software/firmware/source/SoftRF/build/${{ matrix.path }}/
          if-no-files-found: error
