name: build-new-style

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: 'esp32:esp32:esp32s3:PartitionScheme=default_8MB,CPUFreq=80,PSRAM=enabled,FlashMode=qio,FlashSize=8M,DebugLevel=none,CDCOnBoot=cdc,USBMode=hwcdc'
            artifact: 'SoftRF-esp32s3'
            path: 'esp32.esp32.esp32s3'
    env:
      BOARD: ${{ matrix.board }}
      ARTIFACT: ${{ matrix.artifact }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-environment
        with:
          board: ${{ matrix.board }}
      - name: Build SoftRF for platform ${{ matrix.board }}
        run: |
          echo 'Building board ${{ matrix.board }}'
          echo "#define CURRENT_DATE \"$(date +"%Y%m%d")\"" > $GITHUB_WORKSPACE/software/firmware/source/SoftRF/current_date.h
          cd $GITHUB_WORKSPACE
          arduino-cli compile -e -b "${{ matrix.board }}" $GITHUB_WORKSPACE/software/firmware/source/SoftRF
      - uses: actions/upload-artifact@v4
        with:
          name: SoftRF
          path: |
            software/firmware/source/SoftRF/build/${{ matrix.path }}/
          if-no-files-found: error
