name: build-esp32s3

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:

env:
  ESP32S3: 'esp32:esp32:esp32s3:PartitionScheme=default_8MB,CPUFreq=80,PSRAM=enabled,FlashMode=qio,FlashSize=8M,DebugLevel=none,CDCOnBoot=cdc,USBMode=hwcdc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Arduino and Python
        shell: bash
        run: |
          mkdir -p ~/.local/bin
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/.local/bin sh -s nightly-latest

          mkdir $HOME/Arduino
          ln -s $GITHUB_WORKSPACE/software/firmware/source/libraries $HOME/Arduino/libraries

          sudo apt-get update --fix-missing
          sudo apt-get install python3-full

          pip3 install adafruit-nrfutil --user
          
      - name: Install esp32 boards
        shell: bash
        run: |
            arduino-cli config init
            arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
            arduino-cli core update-index
            arduino-cli core install esp32:esp32
      - name: Build SoftRF for ESP32S3
        run: |
          echo 'Building SoftRF for ESP32S3'
          echo "#define CURRENT_DATE \"$(date +"%Y%m%d")\"" > $GITHUB_WORKSPACE/software/firmware/source/SoftRF/current_date.h
          cd $GITHUB_WORKSPACE
          arduino-cli compile -e -b "$EPS32S3" $GITHUB_WORKSPACE/software/firmware/source/SoftRF
      - uses: actions/upload-artifact@v4
        with:
          name: SoftRF-ESP32S3
          path: |
            software/firmware/source/SoftRF/build/esp32.esp32.esp32s3/
          if-no-files-found: error
